package com.ifindyouvideo.videos

import scala.concurrent.future
import scala.concurrent.Future
import scala.concurrent.duration._
import scala.concurrent.ExecutionContext.Implicits.global
import org.joda.time.DateTime
import com.ifindyouvideo.database.Database

class UserRepo {
  def getUser(id: String): Option[User] = Some(User("dummy"))
}

class VideoRepo {
  import VideoRepo._

  def getVideo(id: String): Option[Video] = videos.find(v => v.id == id)

  def findVideos(latitude: BigDecimal, longitude: BigDecimal, radius: String) = videos

  def get(id: String): Future[Option[Video]] = Database.videos.getById(id)

  def getByYearMonthCity(y: Int, m: Int, city: String): Future[List[Video]]  = {
    (cities get city) match {
      case Some(Bounds(nw, se)) => getByYearMonthLocation(y, m, nw, se)
      case None => future { Nil }
    }
  }

  def getByYearMonthLocation(y: Int, m: Int, nw: Location, se: Location): Future[List[Video]] =
    Database.videosByGeohash.getByYearMonthLocation(y, m, nw, se)
}

case class UserContext(userRepo: UserRepo, videoRepo: VideoRepo) {
  def user = User("dummy")
  def location = Some(Location(59.288331692,-135.637207031,0))

  def getAvailableCities: List[String] = VideoRepo.cities.keySet.toList
  def getCityBounds(city: String): Option[Bounds] = VideoRepo.cities get city
}

object VideoRepo {
  val cities = Map(
    "Vancouver, BC" -> Bounds(Location(49.314076,-123.224759,0), Location(49.198177,-123.023068,0)),
    "San Francisco, CA" -> Bounds(Location(37.929771, -123.166067,0), Location(37.693129, -122.327915,0)),
    "Seattle, WA" -> Bounds(Location(47.734145,-122.435908,0), Location(47.495551,-122.235903,0))
  )

  val videos = List(
    Video(
      id = "IXdNnw99-Ic",
      title = "Pink Floyd - Wish You Were Here",
      description = "Pink Floyd, Wish You Were Here (1975)\r\n\r\nSo, so you think you can tell\r\nHeaven from Hell,\r\nBlue skys from pain.\r\nCan you tell a green field\r\nFrom a cold steel rail?\r\nA smile from a veil?\r\nDo you think you can tell?\r\n\r\nAnd did they get you to trade\r\nYour heros for ghosts?\r\nHot ashes for trees?\r\nHot air for a cool breeze?\r\nCold comfort for change?\r\nAnd did you exchange\r\nA walk on part in the war\r\nFor a lead role in a cage?\r\n\r\nHow I wish, how I wish you were here.\r\nWe're just two lost souls\r\nSwimming in a fish bowl,\r\nYear after year,\r\nRunning over the same old ground.\r\nWhat have we found?\r\nThe same old fears.\r\nWish you were here.",
      publishedAt = new DateTime("2006-04-05T07:04:12.000Z"),
      tags = List("pink",
     "floyd",
     "wish",
     "you",
     "were",
     "here",
     "vancouver",
     "Pink Floyd (Musical Group)",
     "manofletters"),
      location = Location(49.19918384851,-123.142061234,0.0),
      channel = Channel("UC7xLkTeEnzQoDOyHuSYyCmg", "chartrand"),
      thumbnails = Thumbnails(
        Some(Image("https://i.ytimg.com/vi/IXdNnw99-Ic/default.jpg", 120, 90)),
        Some(Image("https://i.ytimg.com/vi/IXdNnw99-Ic/mqdefault.jpg", 320, 180)),
        Some(Image("https://i.ytimg.com/vi/IXdNnw99-Ic/hqdefault.jpg", 480, 360)),
        None,None),
      statistics = Statistics("69742063","183814","5476","0","39676")
    ),
    Video(
      id = "YLDbGqJ2KYk",
      title = "Kitten Surprise! (How to Break Up a Cat Fight!) THE ORIGINAL!",
      description = "Tweet this video! http://clicktotweet.com/ffTFk\r\n\r\nBecome a fan on Facebook! \r\nhttp://www.facebook.com/pages/Kitten-Surprise-How-To-Break-Up-A-Cat-Fight/107431422262?created#/pages/Kitten-Surprise-How-To-Break-Up-A-Cat-Fight/107431422262?ref=mf\r\n\r\n\r\n*Relax - the kitten did not drink cow's milk - he drank KMR (Kitten Milk Replacer)\r\n\r\n*No, the kitten was not sick or poisoned nor was this planned, he just drank too much milk.\r\n\r\n*Yes, I know they are not really fighting, it's just a witty title. \r\n\r\nThe kittens have been shown on: The Tonight Show with Jay Leno, DJ and the Fro, Spike Tv, and more to come!",
      publishedAt = new DateTime("2007-08-09T03:13:23.000Z"),
      tags = List("kitten",
     "surprise",
     "how",
     "to",
     "break",
     "up",
     "cat",
     "fight",
     "cute",
     "surprised",
     "kitty",
     "tickle",
     "jazz",
     "hands",
     "animal",
     "funny",
     "comedy",
     "puppy",
     "baby",
     "dog",
     "small",
     "little",
     "adorable",
     "video",
     "rozzzafly",
     "Pets",
     "Cats"),
      location = Location(49.27379820507658,-123.159375,0.0),
      channel = Channel("UCRAPFzv_A0Pb3OyjvPObM-g", "Freyablaze"),
      thumbnails = Thumbnails(
        Some(Image("https://i.ytimg.com/vi/YLDbGqJ2KYk/default.jpg", 120, 90)),
        Some(Image("https://i.ytimg.com/vi/YLDbGqJ2KYk/mqdefault.jpg", 320, 180)),
        Some(Image("https://i.ytimg.com/vi/YLDbGqJ2KYk/hqdefault.jpg", 480, 360)),
        None,None),
      statistics = Statistics("32049462","67679","6396","0","34328")
    ),
    Video(
      id = "-DvdcrcihBA",
      title = "Weird Ass Fish",
      description =
        "Weird fish we caught in 1200 feet of water off of neah bay,wa.\r\n it was already dead when we caught it.",
      publishedAt = new DateTime("2011-09-14T17:13:24.000Z"),
      tags = List("Early Bob Dyaln Blues Album","Bob Dylan","bob dylan","bob dylan album","blues","collection","cover","classical guitar","nylon-string guitar","harmonica","vocal","Crash on the Levee","Down the Highway","From a Buick 6","Long Distance Operator","Maggie's Farm","Outlaw Blues","Sitting on a Barbed Wire Fence","Watchin' The River Flow","acoustic","music","art","fine art","drawing","drawings","painting","digital art","oil painting","creative","artist","Cover Version","Paint","Guitar","Draw","Acoustic Music (Musical Genre)"),
      location = Location(49.25,-123.17,0.0),
      channel = Channel("UCoAOu40g8aE81WCb_lk2gzw", "A Channel Title"),
      thumbnails = Thumbnails(
        Some(Image("https://i.ytimg.com/vi/IrgSkA8wOSw/default.jpg", 120, 90)),
        Some(Image("https://i.ytimg.com/vi/IrgSkA8wOSw/mqdefault.jpg", 320, 180)),
        Some(Image("https://i.ytimg.com/vi/IrgSkA8wOSw/hqdefault.jpg", 480, 360)),
        Some(Image("https://i.ytimg.com/vi/IrgSkA8wOSw/sddefault.jpg", 640, 480)),
        None),
      statistics = Statistics("300542","544","49","0","95")
    ),
    Video(
      id = "Qm1edxnM8Xc",
      title = "Mr krabs dance robot for 3 minutes!",
      description = "the coolest dance ever in spongebob and the best song ever in one video OMG",
      publishedAt = new DateTime("2010-11-04T14:31:55.000Z"),
      tags = List(  "blob fish",
     "weird ass fish",
     "deep sea fishing",
     "trawling",
     "rare",
     "odd",
     "strange",
     "Crazy",
     "Silly",
     "Funny",
     "Weird",
     "Fish",
     "worlds",
     "strangest",
     "fish",
     "ugliest",
     "ugly",
     "deep",
     "sea",
     "deadly",
     "unknown",
     "creatures",
     "monsters"),
      location = Location(49.2,-123.13,0.0),
      channel = Channel("UCtSS-ftrdTW3VuKKSmD2olQ", "Jason Todd Roberts"),
      thumbnails = Thumbnails(
        Some(Image("https://i.ytimg.com/vi/-DvdcrcihBA/default.jpg", 120, 90)),
        Some(Image("https://i.ytimg.com/vi/-DvdcrcihBA/mqdefault.jpg", 320, 180)),
        Some(Image("https://i.ytimg.com/vi/-DvdcrcihBA/hqdefault.jpg", 480, 360)),
        None,None),
      statistics = Statistics("22908563","3296","4373","0","8067")
    ),
    Video(
      id = "pB9CueSNuH0",
      title = "FINGER FAMILY SONG ♫ | Nursery Rhyme | Pancake Manor",
      description = "Like Mama's retro dress? Peek in her closet: http://pancakemanor.com/dresses\nGet the Song! : http://bit.ly/iTunes-PancakeManor\nOur DVD and CDs! : http://shop.pancakemanor.com\nIt's Pancake Manor's take on the classic \"Finger Family\" nursery rhyme. Sing along as Zach and Mama take you through the various family members, plus some new surprises! \nThis version © Billy Reid/ Reb Stevenson 2015\n* * *\nVisit Us : http://pancakemanor.com\nFacebook : http://facebook.com/pancakemanor\niTunes : http://bit.ly/iTunes-PancakeManor\nInstagram : http://instagram.com/pancakemanor\n* * *\nProduced by Billy Reid & Reb Stevenson\nMore to come! Make sure to SUBSCRIBE for more of PANCAKE MANOR!\n* * *\nLyrics :\nNew lyrics and chorus © 2015 Billy Reid/ Reb Stevenson\nDaddy Finger, Daddy Finger\nWhere are you?\nHere I am, here I am. How do you do!\nMommy Finger, Mommy Finger\nWhere are you?\nHere I am, here I am. How do you do!\nBrother Finger, Brother Finger\nWhere are you?\nHere I am, here I am. How do you do!\nSister Finger, Sister Finger\nWhere are you?\nHere I am, here I am. How do you do!\nBaby Finger, Baby Finger\nWhere are you?\nOoo-goo, Eee-geee, a gah, goo-goo\nFive fingers, Five Fingers\nWe found you\nHere we are, here we are\nWe love you!\nFinger puppets are so much fun\nWhen you meet them one by one\nNo legs, they can't stand\nThat's why they need a hand\nZach Finger, Zach Finger\nWhere are you?\nHere I am, here I am. How do you do!\nReggie Finger, Reggie Finger\nWhere are you?\nHere I am, here I am. How do you do!\nLulu Finger, Lulu Finger\nWhere are you?\nHere I am, here I am. How do you do!\nMonster Finger, Monster Finger\nWhere are you?\nHere I am, here I am. How do you do!\n(meow)\nMonkey Finger, Finger\nWhere are you?\nOooOooOOOooooOooooOoooh!\nTen fingers, Ten Fingers\nWe found you\nHere we are, here we are\nWe love you!\nFinger puppets are so much fun\nWhen you meet them one by one\nNo legs, they can't stand\nThat's why they need a hand..or foot!",
      publishedAt = new DateTime("22015-03-31T04:09:07.000Z"),
      tags = List("finger family",
     "five finger",
     "nursery rhymes",
     "nursery",
     "rhymes",
     "finger",
     "five",
     "traditional",
     "kids songs",
     "baby songs",
     "songs",
     "for",
     "children",
     "childrens",
     "children’s",
     "HD",
     "baby",
     "rhyme",
     "lyrics",
     "song",
     "video",
     "kids",
     "animation",
     "babies",
     "parents",
     "toddlers",
     "家傳戶曉高質數兒歌獻給你的寶寶",
     "Babies (Composition)",
     "Nursery Rhyme (Literature Subject)",
     "zach and reggie",
     "kindergarten",
     "pancake manor",
     "childrens songs",
     "children's songs"),
      location = Location(49.288331692,-123.177207031,0.0),
      channel = Channel("UCDBQdJsUA9i8Had_jXCP0bg", "Pancake Manor"),
      thumbnails = Thumbnails(
        Some(Image("https://i.ytimg.com/vi/pB9CueSNuH0/default.jpg", 120, 90)),
        Some(Image("https://i.ytimg.com/vi/pB9CueSNuH0/mqdefault.jpg", 320, 180)),
        Some(Image("https://i.ytimg.com/vi/pB9CueSNuH0/hqdefault.jpg", 480, 360)),
        Some(Image("https://i.ytimg.com/vi/pB9CueSNuH0/sddefault.jpg", 640, 480)),
        Some(Image("https://i.ytimg.com/vi/pB9CueSNuH0/maxresdefault.jpg", 1280, 720))),
      statistics = Statistics("22167214","11845","5886","0","798")
    ),
    Video(
      id = "UC2ZSx2955RgwuzlJmnaculw",
      title = "Test",
      description = "This self breast massage technique is designed to move lymph out of the breast as an aid in woman's health. Reducing toxins from the breast tissues is believed to reduce breast cancer risk for cancers related to toxins.",
      publishedAt = new DateTime("2006-04-05T07:04:12.000Z"),
      tags = List(
        "pink",
        "floyd",
        "wish",
        "you",
        "were",
        "here",
        "vancouver",
        "Pink Floyd (Musical Group)",
        "manofletters"
      ),
      location = Location(49.1618384851,-123.142061234,0.0),
      channel = Channel("UC7xLkTeEnzQoDOyHuSYyCmg", "chartrand"),
      thumbnails = Thumbnails(
        Some(Image("https://i.ytimg.com/vi/IXdNnw99-Ic/default.jpg", 120, 90)),
        Some(Image("https://i.ytimg.com/vi/IXdNnw99-Ic/mqdefault.jpg", 320, 180)),
        Some(Image("https://i.ytimg.com/vi/IXdNnw99-Ic/hqdefault.jpg", 480, 360)),
        None,None),
      statistics = Statistics("69742063","183814","5476","0","39676")
    ),
    Video(
      id = "5ioZC5CMKLM",
      title = "FIVE LITTLE MONKEYS JUMPING ON THE BED  ♫ | Nursery Rhyme | Pancake Manor",
      description = "Song on iTunes : https://itunes.apple.com/us/artist/pancake-manor/id455710128?uo=4&at=11lSge\nGet our CD & DVD here! : http://pancake-manor.myshopify.com/collections/all\nZach and Reggie sing the classic nursery rhyme Five Little Monkeys Jumping on the Bed! Enjoy this extended song with your toddler and sing along! Featuring a new ending that your child will love.\nThis version ©2014 Billy Reid and Reb Stevenson\nSpecial thanks to http://dollsanddaydreams.com for their adorable monkey patterns!\n* * *\nVisit Us : http://pancakemanor.com\nFacebook : http://facebook.com/pancakemanor\nTwitter : http://twitter.com/pancakemanor\n\n* * *\nProduced by Billy Reid & Reb Stevenson\nMore to come! Make sure to SUBSCRIBE for more of PANCAKE MANOR!\n* * *\n\nLyrics :\n\nFive little monkeys jumping on the bed\nOne fell off and bumped his head\nMama called the doctor and the doctor said\n\"No more monkeys jumping on the bed!\"\n\nFour little monkeys jumping on the bed\nOne fell off and bumped her head\nMama called the doctor and the doctor said\n\"No more monkeys jumping on the bed!\"\n\nThree little monkeys jumping on the bed\nOne fell off and bumped his head\nMama called the doctor and the doctor said\n\"No more monkeys jumping on the bed!\"\n\nThere were five, there were four, there were three\nHow many left? count with me!\nOne! Two!\n\nTwo little monkeys jumping on the bed\nOne fell off and bumped his head\nMama called the doctor and the doctor said\n\"No more monkeys jumping on the bed!\"\n\nOne little monkey standing on the bed\n\" I don't want to bump my head\"\nShe got off and danced instead\nNo more monkeys jumping on the bed\n\nNo more monkeys jumping on the bed\nNone fell off to bump their heads\nDoctor called mama and mama said\n\"No more monkeys are jumping on the bed!\"",
      publishedAt = new DateTime("2014-09-14T18:03:05.000Z"),
      tags = List(   "children's music",
     "kids songs",
     "zach and reggie",
     "children's songs",
     "pancake manor",
     "rhymes",
     "child",
     "autism",
     "ASD",
     "autistic",
     "song",
     "kids",
     "learn",
     "english",
     "英",
     "文兒",
     "歌children",
     "ESL",
     "EFL",
     "英語",
     "えいごであそぼ",
     "こども英会話",
     "子供",
     "英会話",
     "homeschool",
     "で",
     "遊ぼう",
     "toddlers",
     "lesson",
     "歌",
     "曲",
     "みんなの歌",
     "kindergarten",
     "lessons",
     "cartoons",
     "education",
     "family",
     "teacher",
     "parents",
     "student",
     "teachers",
     "language",
     "少儿英语",
     "animation",
     "art",
     "puppets",
     "muppets",
     "original",
     "educational",
     "canadian",
     "英語教育",
     "教育",
     "NHK",
     "5 little monkeys",
     "five little monkeys",
     "monkeys",
     "Nursery Rhyme (Literature Subject)"),
      location = Location(49.2216003418,-123.167416382,0.0),
      channel = Channel("UCDBQdJsUA9i8Had_jXCP0bg", "Pancake Manor"),
      thumbnails = Thumbnails(
        Some(Image("https://i.ytimg.com/vi/-DvdcrcihBA/default.jpg", 120, 90)),
        Some(Image("https://i.ytimg.com/vi/-DvdcrcihBA/mqdefault.jpg", 320, 180)),
        Some(Image("https://i.ytimg.com/vi/-DvdcrcihBA/hqdefault.jpg", 480, 360)),
        None,None),
      statistics = Statistics("20144972","0","0","0","699")
    ),
    Video(
      id = "WR8jZrc-jhs",
      title = "OLD MACDONALD HAD A FARM - Nursery Rhyme | Pancake Manor",
      description = "Song on iTunes : https://itunes.apple.com/us/album/old-macdonald-had-farm-single/id926417840?uo=4\nZach and Reggie sing the classic nursery rhyme Old MacDonald Had a Farm! This version by Billy Reid ©2014\n* * *\nVisit Us : http://pancakemanor.com\nFacebook : http://facebook.com/pancakemanor\nInstagram : http://instagram.com/pancakemanor\nTwitter : http://twitter.com/pancakemanor\nCDs & DVD here! : http://pancake-manor.myshopify.com/collections/all\n\n* * *\nProduced by Billy Reid & Reb Stevenson\nMore to come! Make sure to SUBSCRIBE for more of PANCAKE MANOR!\nWant more classic children's songs like Old McDonald, let us know!\n* * *",
      publishedAt = new DateTime("2014-04-06T20:51:33.000Z"),
      tags = List( "children's music",
     "kids songs",
     "zach and reggie",
     "children's songs",
     "pancake manor",
     "rhymes",
     "child",
     "song",
     "kids",
     "learn",
     "english",
     "英",
     "文兒",
     "歌children",
     "ESL",
     "EFL",
     "英語",
     "えいごであそぼ",
     "こども英会話",
     "子供",
     "英会話",
     "homeschool",
     "で",
     "遊ぼう",
     "toddlers",
     "lesson",
     "歌",
     "曲",
     "みんなの歌",
     "kindergarten",
     "lessons",
     "cartoons",
     "education",
     "family",
     "teacher",
     "parents",
     "student",
     "teachers",
     "language",
     "少儿英语",
     "animation",
     "art",
     "puppets",
     "muppets",
     "original",
     "educational",
     "canadian",
     "英語教育",
     "教育",
     "NHK",
     "Old MacDonald Had A Farm (Composition)",
     "Old McDonald",
     "Old MacDonald",
     "Nursery Rhyme (Literature Subject)"),
      location = Location(49.4216003418,-123.367416382,0.0),
      channel = Channel("UCDBQdJsUA9i8Had_jXCP0bg", "Pancake Manor"),
      thumbnails = Thumbnails(
        Some(Image("https://i.ytimg.com/vi/WR8jZrc-jhs/default.jpg", 120, 90)),
        Some(Image("https://i.ytimg.com/vi/WR8jZrc-jhs/mqdefault.jpg", 320, 180)),
        Some(Image("https://i.ytimg.com/vi/WR8jZrc-jhs/hqdefault.jpg", 480, 360)),
        Some(Image("https://i.ytimg.com/vi/WR8jZrc-jhs/sddefault.jpg",
        640, 480)),
        Some(Image("https://i.ytimg.com/vi/WR8jZrc-jhs/maxresdefault.jpg",
        1280, 720))),
      statistics = Statistics("18212345","0","0","0","645")
    ),
    Video(
      id = "29UMACdfyZw",
      title = "MACKLEMORE & RYAN LEWIS - \"Irish Celebration\" (Official Music Video)",
      description = "PRODUCED BY - Ryan Lewis\nVIOLIN - Andrew Joslyn\nTRUMPET - Owuor Arunga\nADDITIONAL VOCALS - Tim Haggerty, Noah Goldberg\n\n\nDIRECTOR:  Stephan Gray\nDP - Ryan Purcell\nB CAMERA - Stephan Gray\nC Camera - Ryan Lewis\nAC - William Brody & Conor Hair\nGAFFER - Tred Baylis\nKEY GRIP - Blue Boy\nHAIR/MAKEUP - Shawn Shelton\nPRODUCER - Bret Seeger\nEDIT - Stephan Gray",
      publishedAt = new DateTime("2011-01-26T18:06:54.000Z"),
      tags = List(    "Macklemore and Ryan Lewis",
     "Macklemore",
     "Ryan Lewis",
     "Irish Celebration",
     "Ireland",
     "Seattle",
     "Seattle hip hop",
     "Stephan Gray",
     "Gray Matter",
     "Gray Matter Productions",
     "GMP",
     "Northwest hip hip",
     "Northwest music",
     "seattle music video",
     "new macklemore",
     "macklemore video",
     "macklemore music video"),
      location = Location(49.97379820507658,-123.109375,0.0),
      channel = Channel("UCRAPFzv_A0Pb3OyjvPObM-g", "Freyablaze"),
      thumbnails = Thumbnails(
        Some(Image("https://i.ytimg.com/vi/29UMACdfyZw/default.jpg", 120, 90)),
        Some(Image("https://i.ytimg.com/vi/29UMACdfyZw/mqdefault.jpg", 320, 180)),
        Some(Image("https://i.ytimg.com/vi/29UMACdfyZw/hqdefault.jpg", 480, 360)),
        Some(Image("https://i.ytimg.com/vi/29UMACdfyZw/sddefault.jpg", 480, 360)),
        Some(Image("https://i.ytimg.com/vi/29UMACdfyZw/maxresdefault.jpg", 480, 360))),
      statistics = Statistics("18027549","96264","2032","0","27577")
    ),
    Video(
      id = "O6Xo21L0ybE",
      title = "Polite Bear Waves Hello - a waving bear",
      description =
        "funniest bear i have ever seen.  it is at the Olympic game farm in Washington.",
      publishedAt = new DateTime("2010-06-28T23:54:07.000Z"),
      tags = List("bear",
     "kodiak",
     "grizzley",
     "brown",
     "wave",
     "funny",
     "animal",
     "laugh",
     "polite",
     "hello",
     "goodbye",
     "Zoo",
     "Bears",
     "Big",
     "Say",
     "Teddy",
     "Polite",
     "Bear",
     "Waves",
     "Hello",
     "Pets",
     "cool",
     "awesome",
     "alaska",
     "washington",
     "silly",
     "Capture",
     "Beach",
     "Polar",
     "Lake",
     "Animal (Film Character)",
     "Outdoor Recreation (Interest)",
     "Lunch",
     "Flag",
     "Fantastic",
     "Build"),
      location = Location(49.1364373214,-123.1511271,0.0),
      channel = Channel("UCOtoNaQBWaYsUrQEPEVSryg", "https://i.ytimg.com/vi/NQTplsNldL4/sddefault.jpg"),
      thumbnails = Thumbnails(
        Some(Image("https://i.ytimg.com/vi/NQTplsNldL4/default.jpg", 120, 90)),
        Some(Image("https://i.ytimg.com/vi/NQTplsNldL4/mqdefault.jpg", 320, 180)),
        Some(Image("https://i.ytimg.com/vi/NQTplsNldL4/hqdefault.jpg", 480, 360)),
        Some(Image("https://i.ytimg.com/vi/NQTplsNldL4/sddefault.jpg", 640, 480)),
        None),
      statistics = Statistics("10279344","22179","5060","0","2034")
    )
  )
}
